#!/usr/bin/env node
// jshint camelcase:false
"use strict";

var filter = require("object-filter");
var load = require("./lib/load");
var Store = require("./lib/store");

function isStation(stop) {
  return stop.location_type === "1";
}

var store = new Store();
load(store, __dirname + "/data", function(err) {
  if (err) {
    throw err;
  }
  var stations = filter(store.stops, isStation);
  console.log(JSON.stringify(stations));
});
