#!/usr/bin/env node
"use strict";

var load = require("./lib/load");
var Store = require("./lib/store");

var store = new Store();
load(store, __dirname + "/data", function(err) {
  if (err) {
    throw err;
  }
  console.log(JSON.stringify(store));
});
