#!/usr/bin/env bash

# Usage:
#
# ./update-data http://www.caltrain.com/Assets/GTFS/caltrain/CT-GTFS.zip
#

set -e
zipurl=$1

# Download data
zipbase=`basename $zipurl`
zippath=`mktemp -t "${zipbase}.XXXX"`
curl "$zipurl" -o $zippath

# Delete previous data
rm -rf data/*

# Unpack data into data/ directory
unzip -d ./data/ $zippath
rm $zippath

# Update data.json
npm run dump-data
